--CREATE TABLE EMP
--(
--	EMPNO		NUMBER(4,0)	NOT NULL,
--	ENAME		VARCHAR2(12),
--	JOB		VARCHAR2(10),
--	MGR		NUMBER(4,0),
--	HIREDATE	DATE,
--	SAL		NUMBER(7,2),
--	COMM		NUMBER(7,2),
--	DEPTNO		NUMBER(2,0)	NOT NULL,
--	SPOUSES_NAME	CHAR(10),
--	CONSTRAINT PK_EMPNO PRIMARY KEY(EMPNO)
--);

CREATE TABLE S
(
	S#	CHAR(11),
	SNAME	VARCHAR2(8),
	AGE	NUMBER(3,0),
	SEX	CHAR(2),
	CONSTRAINT PK_S PRIMARY KEY(S#)
);

CREATE TABLE SC
(
	S#	CHAR(11),
	C#	CHAR(5),
	GRADE	NUMBER(3,0),
	CONSTRAINT PK_S_C PRIMARY KEY(S#,C#)
);

CREATE TABLE C
(
	C#	CHAR(5),
	CNAME	VARCHAR2(12),
	TEACHER	VARCHAR2(8),
	CONSTRAINT PK_C PRIMARY KEY(C#)
);

CREATE TABLE PROJECTS
(
	PROJID		NUMBER(4,0),
	P_DESC		VARCHAR2(20),
	P_START_DATE	DATE,
	P_END_DATE	DATE,
	BUDGET_AMOUNT	NUMBER(7,2),
	MAX_NO_STAFF	NUMBER(2,0),
	CONSTRAINT FK_PROJID PRIMARY KEY(PROJID),
	CONSTRAINT CH_END_START  CHECK(P_END_DATE>P_START_DATE)
);

CREATE TABLE ASSIGNMENTS
(
	PROJID		NUMBER(4,0)	NOT NULL,
	EMPNO		NUMBER(4,0)	NOT NULL,
	A_START_DATE	DATE,
	A_END_DATE	DATE,
	BILL_RATE	NUMBER(4,2),
	ASSIGN_TYPE	VARCHAR2(2),
	CONSTRAINT FK_PROJECTS_PROJID FOREIGN KEY(PROJID) REFERENCES PROJECTS(PROJID),
	CONSTRAINT FK_EMPNO FOREIGN KEY(EMPNO) REFERENCES EMP(EMPNO)
);

ALTER TABLE PROJECTS ADD
(
	COMMENTS	LONG
);

ALTER TABLE ASSIGNMENTS ADD
(
	HOURS		NUMBER
);
